# Generated by Django 4.1.4 on 2023-01-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_users_password_alter_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='id_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subject_handled',
            name='subject_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subject_handled',
            name='subject_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
