# Generated by Django 4.1.4 on 2023-01-15 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_faculty_details_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mail_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
