# Generated by Django 4.1.4 on 2023-01-15 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_details',
            name='user_name',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='assessment_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 19, 36, 44, 478203)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='department',
            field=models.CharField(default='department', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='designation',
            field=models.CharField(default='designation', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='id_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='image',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='qualififcation',
            field=models.CharField(default='qualififcation', max_length=200),
        ),
    ]
