# Generated by Django 4.1.4 on 2023-01-15 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_faculty_details_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 19, 54, 53, 302425)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
