# Generated by Django 4.1.4 on 2023-01-15 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_faculty_details_date_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 20, 23, 27, 763219)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='image',
            field=models.ImageField(default='Screenshot_3.png', upload_to='photo/%Y/%m/%d'),
        ),
    ]
