# Generated by Django 4.1.4 on 2023-01-15 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_faculty_details_date_of_join_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty_details',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 20, 28, 34, 272353)),
        ),
    ]
