# Generated by Django 4.1.4 on 2023-01-16 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_faculty_details_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='department',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 7, 59, 33, 366690)),
        ),
    ]
