# Generated by Django 4.1.4 on 2023-01-16 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_subjects_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='discription',
            field=models.CharField(default='No Discription yet.', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 8, 2, 46, 91439)),
        ),
    ]
