# Generated by Django 4.1.4 on 2023-01-16 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_subject_handled_image_subjects_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 9, 45, 11, 861353)),
        ),
        migrations.AlterField(
            model_name='subject_handled',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
