# Generated by Django 4.1.4 on 2023-01-16 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_image_subject_handled_subject_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_handled',
            name='subject_image',
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 9, 55, 58, 57820)),
        ),
    ]
