# Generated by Django 4.1.4 on 2023-01-16 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_subject_handled_subject_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 10, 0, 18, 661061)),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='department',
            field=models.CharField(max_length=200),
        ),
    ]
