# Generated by Django 4.1.4 on 2023-01-16 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_faculty_details_date_of_join_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_details',
            name='bio',
            field=models.CharField(default='No Bio yet.', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty_details',
            name='user_name',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 11, 15, 10, 47784)),
        ),
    ]
