# Generated by Django 4.1.4 on 2023-01-17 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_faculty_details_date_of_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_handled',
            name='faculty_id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 8, 31, 40, 290113)),
        ),
        migrations.AlterField(
            model_name='subject_handled',
            name='actual_pass',
            field=models.CharField(default='10', max_length=200),
        ),
        migrations.AlterField(
            model_name='subject_handled',
            name='target_pass',
            field=models.CharField(default='10', max_length=200),
        ),
    ]
