# Generated by Django 4.1.4 on 2023-01-17 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_subject_handled_faculty_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 10, 28, 2, 105580)),
        ),
        migrations.AlterField(
            model_name='subject_handled',
            name='subject_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subject_handled',
            name='subject_name',
            field=models.CharField(max_length=200),
        ),
    ]
