# Generated by Django 4.1.4 on 2023-01-17 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_faculty_details_date_of_join_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField()),
                ('image', models.ImageField(default='images/user_image.png', upload_to='photo/%Y/%m/%d')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2023, 1, 17, 12, 51, 15, 589267))),
                ('designation', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('coming_from', models.CharField(max_length=200)),
                ('mail_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='guest_lecture',
            name='faculty_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 12, 51, 15, 589267)),
        ),
        migrations.AlterField(
            model_name='guest_lecture',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.details'),
        ),
    ]
