# Generated by Django 4.1.4 on 2023-01-17 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_details_guest_lecture_faculty_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 7, 24, 59, 772909, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 7, 24, 59, 767903, tzinfo=datetime.timezone.utc)),
        ),
    ]
