# Generated by Django 4.1.4 on 2023-01-17 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_details_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 7, 36, 38, 661555, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='date_of_join',
            field=models.DateField(default=datetime.datetime(2023, 1, 17, 7, 36, 38, 661555, tzinfo=datetime.timezone.utc)),
        ),
    ]
